CREATE TYPE game_type_one as ENUM ('Live', 'Online');
CREATE TYPE game_type_two as ENUM ('Cash', 'Tournament');

CREATE TABLE poker_sessions (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  game_type_one game_type_one NOT NULL,
  game_type_two game_type_two NOT NULL,
  date_played TIMESTAMP DEFAULT now() NOT NULL,
  small_blind NUMERIC NOT NULL,
  big_blind NUMERIC NOT NULL,
  buy_in NUMERIC NOT NULL,
  cashed_out NUMERIC NOT NULL,
  session_length NUMERIC NOT NULL,
  notes TEXT
);